const SECONDS_IN_HOUR = 60 * 60;
const MILLISECONDS_IN_SECOND = 1000;
const TWO_WEEKS_IN_MILLISECONDS = 14 * 24 * 60 * 60 * 1000;
const SECONDS_IN_A_DAY = 24 * 60 * 60;

export {
  MILLISECONDS_IN_SECOND,
  SECONDS_IN_A_DAY,
  SECONDS_IN_HOUR,
  TWO_WEEKS_IN_MILLISECONDS,
};
