name: Next.js build and test
on:
  push:
    branches:
      - main
      - dev 
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
                
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install system dependencies
        run: |
              sudo apt-get update
              sudo apt-get install -y libgtk-4-1 libgraphene-1.0-0 libwoff1 libvpx7 libevent-2.1-7 \
              libopus0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgstreamer-gl1.0-0 \
              libflite1 libavif0 libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 \
              libgles2 libx264-dev
      - name: Install playwright
        run: npx playwright install
      - name: Install playwright dependencies
        run: npx playwright install-deps
      - name: Run tests
        run: npm test